/// generated by ts2fable and transformer
module rec RailwayRoute

open System


type BetriebsstelleRailwayRoutePosition = {
    STRECKE_NR: int option
    RICHTUNG: float
    KM_I: float
    KM_L: string
    BEZEICHNUNG: string
    STELLE_ART: string
    KUERZEL: string
    GK_R_DGN: float
    GK_H_DGN: float
    GEOGR_BREITE: float
    GEOGR_LAENGE: float
    maxSpeed: float option
}
type BetriebsstelleWithRailwayRoutePosition = {
    ds100_ref: string
    name: string
    railwayRoutePosition: BetriebsstelleRailwayRoutePosition option
}
type RailwayRouteOfTrip = {
    railwayRouteNr: int option
    from: BetriebsstelleWithRailwayRoutePosition option
    ``to``: BetriebsstelleWithRailwayRoutePosition option
}
type RailwayRouteOfTripResult = {
    railwayRoutes: array<RailwayRouteOfTrip>
    missing: float
}

